### ISSUE TITLE
corosync (v3)  ring error - debian 10

### ISSUE THREAD

**Issue by kilida2020** [ClusterLabs/ha_cluster_exporter#147] opened 2020-04-09 13:06 UTC
Hi,

I am not able to collect the metrics of the corosync ring, present the message below:

INFO[0000] Serving metrics on 0.0.0.0:9664
DEBU[0004] Collecting corosync metrics...
DEBU[0004] Collecting pacemaker metrics...
DEBU[0004] Collecting DRBD metrics...
WARN[0004] cannot parse ring status: corosync-cfgtool returned unexpected output: Printing link status.
Local node ID 1
LINK ID 0
        addr    = 128.1.0.86
        status  = OK

Thanks,

**Comment by kilida2020** [comment] 2020-04-09 20:00
Hi,

I can't collect the metrics for the corosync ring, please display the message below:

INFO [0000] Displaying metrics at 0.0.0.0:9664
DEBU [0004] Collecting corosync metrics ...
DEBU [0004] Collecting pacemaker metrics ...
DEBU [0004] Collecting DRBD metrics ...
WARN [0004] cannot analyze the status of the ring: corosync-cfgtool returned an unexpected exit: Printing link status.
Local node ID 1
LINK 0
address = 128.1.0.86
status = OK

Thanks

**Comment by MalloZup** [comment] 2020-04-10 10:42
@kilida2020 thx for issue. 

I have checked your issue. IT seems that you don't have any RING in your clusters, so that is why you get this warning.

can you run
```
 sudo corosync-cfgtool -s
```


you should have something like this 
```
 sudo corosync-cfgtool -s
Printing ring status.
Local node ID 33554442
RING ID 0
	id	= 10.0.0.1
	status	= ring 0 active with no faults```

If you have no ring this means you need to configure corosync. (check upstream docs)

Let me know

Best 
:sun_with_face:

**Comment by kilida2020** [comment] 2020-04-13 17:38
Hi,

This is my corosync configuration file.
You can analyze, I see that the RING is configured.

totem {
  version: 2
  cluster_name: debian
  secauth: off
  transport:udpu
  interface {
    ringnumber: 0
    bindnetaddr: 128.1.0.0
    broadcast: yes
    mcastport: 5405
  }
}

nodelist {
  node {
    ring0_addr: 128.1.0.86
    name: srvlabm
    nodeid: 1
  }
  node {
    ring0_addr: 128.1.0.87
    name: srvlabs
    nodeid: 2
  }
}

quorum {
  provider: corosync_votequorum
  two_node: 1
  wait_for_all: 1
  last_man_standing: 1
  auto_tie_breaker: 0
}

**Comment by diegoakechi** [comment] 2020-04-14 15:21
@kilida2020 as requested by @MalloZup, can you post the output of the command below:
` sudo corosync-cfgtool -s`

**Comment by kilida2020** [comment] 2020-04-14 17:50
root@srvlabm:/etc/vbox# corosync-cfgtool -s
Printing link status.
Local node ID 1
LINK ID 0
        addr    = 128.1.0.86
        status  = OK

**Comment by MalloZup** [comment] 2020-04-15 09:31
@kilida2020 thx. can you tell me which version of pkg corosync etc,  are you using since I don't have any  debian 10 machine? thx lot sofar :+1:

**Comment by kilida2020** [comment] 2020-04-15 10:47
root@srvlabm:/home/master# corosync -v
Corosync Cluster Engine, version '3.0.1'
Copyright (c) 2006-2018 Red Hat, Inc.

**Comment by MalloZup** [comment] 2020-04-15 16:02
@kilida2020 ok thx sofar. I have investigated a bit is that the new corosync v3 brings a new API where we depends on.

We need to fix this in near future.

For example the `RING` is now called `LINK` and the status has changed.

**Comment by stefanotorresi** [comment] 2020-04-21 12:55
I will mark this as "new feature/enhancement" because supporting corosync3 was not in the plans. 

This is certainly worth pursuing, and more generally supporting different versions of the tools we leverage, but I'm afraid we don't have the capacity right now, so contributions are welcome...

**Comment by stefanotorresi** [comment] 2020-04-30 13:54
@kilida2020 I can confirm that support for Corosync v3 will come at some point in the future, however
#151 introduced a refactoring that should make implementing a new cfgtool parser easy enough, so feel free to have a stab at it with a PR; otherwise, you'll have to wait until this feature enters our planning, which may take weeks/months.

**Comment by vvidic** [comment] 2020-05-09 13:07
Another problem with Corosync 3.0.3 seems to be that the Ring ID field has changed from Id/Seq:

```
Quorum information
------------------
Date:             Sat May  9 12:58:29 2020
Quorum provider:  corosync_votequorum
Nodes:            1
Node ID:          1
Ring ID:          1.5
Quorate:          Yes

Votequorum information
----------------------
Expected votes:   1
Highest expected: 1
Total votes:      1
Quorum:           1  
Flags:            Quorate 

Membership information
----------------------
    Nodeid      Votes Name
         1          1 node1 (local)
```

**Comment by stefanotorresi** [comment] 2020-05-29 10:15
this should be fixed by #156.
@kilida2020 could you please test against the latest `master` branch?

**Comment by kilida2020** [comment] 2020-06-04 21:27
@stefanotorresi

Hi,
Where do I download the corrected code for test? On the github?
Thanks,

**Comment by rmakram-ims** [comment] 2020-06-04 21:46
it's in the master branch, you can use the installation instructions on the readme, easiest way is to use "go get github.com/ClusterLabs/ha_cluster_exporter"

**Comment by kilida2020** [comment] 2020-06-04 22:10
@rmakram-ims

Hi,
Still reporting the same error

root@srvlabs:~/work/bin# ha_cluster_exporter
INFO[0000] Using config file: /etc/ha_cluster_exporter.yaml
INFO[0000] Pacemaker collector registered
INFO[0000] Corosync collector registered
WARN[0000] could not initialize SBD collector: '/usr/sbin/sbd' does not exist
INFO[0000] DRBD collector registered
INFO[0000] Serving metrics on 0.0.0.0:9664
WARN[0005] cannot parse ring status: corosync-cfgtool returned unexpected output: Printing link status.
Local node ID 2
LINK ID 0
        addr    = 128.1.0.87
        status  = OK
WARN[0006] cannot parse ring status: corosync-cfgtool returned unexpected output: Printing link status.

**Comment by kilida2020** [comment] 2020-06-04 22:20
@rmakram-ims

Sorry, I tested it with an old file. It worked !!!!

root@srvlabs:~/work/bin# ./ha_cluster_exporter
INFO[0000] Using config file: /etc/ha_cluster_exporter.yaml
INFO[0000] Pacemaker collector registered
INFO[0000] Corosync collector registered
WARN[0000] could not initialize SBD collector: '/usr/sbin/sbd' does not exist
INFO[0000] DRBD collector registered
INFO[0000] Serving metrics on 0.0.0.0:9664

**Comment by rmakram-ims** [comment] 2020-06-04 22:20
I was able to test it with my changes and with the latest from the master branch on corosync version 3.0.3.

**Comment by rmakram-ims** [comment] 2020-06-04 22:20
glad to see it working!

**Comment by kilida2020** [comment] 2020-06-04 22:22
Me more, very good work!

Thanks

**Comment by rmakram-ims** [comment] 2020-06-04 22:23
anytime, I needed this as well, decided it was worth investing the time into it. The maintainers of this repo reviewed it very quickly!

**Comment by kilida2020** [comment] 2020-06-04 22:27
Yes, congratulations to everyone. I really needed this solution.
Thanks again

**Comment by MalloZup** [comment] 2020-06-05 08:02
great happy it worked out! best

**Comment by MalloZup** [comment] 2020-06-05 08:02
I think we can close this issue afaik>

**Comment by stefanotorresi** [comment] 2020-06-05 08:09
you, thank you all for reporting!

**Closed by stefanotorresi** 2020-06-05 08:09 UTC
Labels: enhancement, help wanted
