### ISSUE TITLE
"'corosync' collector scrape failed: corosync parser error: could not parse members in corosync-quorumtool output: could not find membership information"

### ISSUE THREAD

**Issue by iglov** [ClusterLabs/ha_cluster_exporter#171] opened 2020-07-17 11:06 UTC
```
OS ubuntu 20.04

# prometheus-ha-cluster-exporter --version
version 1.1.0+git.1594637514.c1eae0c
built with go1.14.4 linux/amd64 2020-07-13T11:10:51+00:00

# corosync -v
Corosync Cluster Engine, version '3.0.3'
Copyright (c) 2006-2018 Red Hat, Inc.

# corosync-quorumtool -V
corosync-quorumtool version: 3.0.3

# corosync-quorumtool -s
Quorum information
------------------
Date:             Fri Jul 17 14:00:20 2020
Quorum provider:  corosync_votequorum
Nodes:            2
Node ID:          1
Ring ID:          1.16d
Quorate:          Yes

Votequorum information
----------------------
Expected votes:   3
Highest expected: 3
Total votes:      3
Quorum:           2  
Flags:            Quorate Qdevice 

Membership information
----------------------
    Nodeid      Votes    Qdevice Name
         1          1    A,V,NMW node1.local (local)
         2          1    A,V,NMW node2.local
         0          1            Qdevice
```

**Comment by stefanotorresi** [comment] 2020-07-17 11:22
duplicate of #170

**Closed by stefanotorresi** 2020-07-17 11:22 UTC

**Comment by iglov** [comment] 2020-07-17 11:25
@stefanotorresi you should change there issue name - remove version of corosync, this is confusing.

**Comment by stefanotorresi** [comment] 2020-07-17 11:32
good point, @iglov, done!

**Comment by iglov** [comment] 2020-07-17 11:36
@stefanotorresi thx 4 ur time!
